version: 2
updates:

  # Config for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
    assignees:
      - "emaarco"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
          - "major"

  # Config for docs website (npm)
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    assignees:
      - "emaarco"
    groups:
      docs-dependencies:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
          - "major"
